
task: "segmentation"
epochs: 500
checkpoint_step: 10
validate_after: 1
autocast: False
#eval_checkpoint: 
#eval_weights: 

training:

  n_classes: 21
  batch_acc: 1
  batch_size: 32
  num_worker: 8
  pin_memory: True
  forward_hooks: False
  #checkpoint: 
  caffe_pretrained: False
  max_iter: null #max total batch iteration

  loss_function:
    ce: null
    params:
      reduction: "mean"

  optim:
    SGD:
      momentum: 0.9
      weight_decay: 0.001
      lr: 1.0e-2
  
  lr_scheduler:
    PolynomialLR: 
      total_iters: 500
      power: 0.9

      


