
task: "segmentation"
epochs: 1000
checkpoint_step: 50
validate_after: 1
autocast: False
#eval_checkpoint: 
#eval_weights: 

training:

  find_best_lr: False
  n_classes: 21
  batch_acc: 1
  batch_size: 32
  num_worker: 8
  pin_memory: True
  forward_hooks: False
  checkpoint: /projects/SemSeg/logs/UNET/20240403_095026_testWOResizeNoDeconv/checkpoints/last.pt
  caffe_pretrained: False
  max_iter: null #max total batch iteration

  loss_function:
    ce: null
    params:
      reduction: "mean"
      ignore_index: 21

  optim:
    SGD:
      momentum: 0.9
      weight_decay: 0.0005
      lr: 1.0e-2

    # Adam:
    #   weight_decay: 0.005
    #   lr: 5.0e-4

  lr_scheduler:
    PolynomialLR: 
      total_iters: 1000
      power: 0.9

      


