
task: "segmentation"
epochs: 800
checkpoint_step: 50
validate_after: 1
autocast: False
n_classes: 21
eval_checkpoint: /projects/SemSeg/logs/UNET/20240412_075200_NoConvTranNotBatchNorm/checkpoints/best.pt 
#eval_weights: 

training:

  find_best_lr: False
  batch_acc: 1
  batch_size: 32
  num_worker: 8
  pin_memory: True
  forward_hooks: False
  checkpoint: /projects/SemSeg/logs/UNET/20240415_213225_Restart_NoConvTranNotBatchNorm/checkpoints/last.pt
  caffe_pretrained: False
  max_iter: null #max total batch iteration

  loss_function:
    ce: null
    params:
      reduction: "mean"
      ignore_index: 21

  optim:
    # SGD:
    #   momentum: 0.9
    #   weight_decay: 0.0005
    #   lr: 5.0e-4

    Adam:
      weight_decay: 0.0005
      lr: 5.0e-5

  # lr_scheduler:
  #   PolynomialLR: 
  #     total_iters: 1600
  #     power: 0.9

      


