
task: "segmentation"
epochs: 400
checkpoint_step: 1
validate_after: 1
autocast: False

training:

  n_classes: 21
  batch_acc: 1
  batch_size: 1
  num_worker: 4
  pin_memory: True
  forward_hooks: False
  #checkpoint: "C:\\Users\\anton\\Downloads\\checkpoints11.pt"
  caffe_pretrained: True
  max_iter: 10000 #max total batch iteration

  loss_function:
    ce: null
    params:
      reduction: "sum"

  optim:
    SGD:
      fcn: True
      momentum: 0.99
      weight_decay: 0.0005
      lr: 0.0000000001


