
task: "segmentation"
epochs: 200
checkpoint_step: 20

training:

  n_classes: 21
  batch_acc: 1
  autocast: True
  batch_size: 2
  
  loss_function:
    ce: null

  optim:
    SGD: 
      momentum: 0.9
      weight_decay: 0.0005
      lr: 0.0001


