
task: "segmentation"
epochs: 600
checkpoint_step: 50
validate_after: 1
autocast: False
n_classes: 21
device: "cuda"
# eval_checkpoint: 
#eval_weights: 

training:

  find_best_lr: False
  batch_acc: 1
  batch_size: 32
  num_worker: 8
  pin_memory: True
  forward_hooks: False
  #checkpoint: 
  max_iter: null #max total batch iteration
  aux_loss_weight: [1.0, 1.0, 1.0, 1.0]

  loss_function:
    ce: null
    params:
      reduction: "mean"
      ignore_index: 21

  optim:
    SGD:
      momentum: 0.9
      weight_decay: 0.0005
      lr: 1.0e-4

#     Adam:
#       weight_decay: 0.0005
#       lr: 1.0e-4

  lr_scheduler:
    PolynomialLR: 
      total_iters: 600
      power: 0.9

      


