
task: "segmentation"
epochs: 600
checkpoint_step: 50
validate_after: 1
autocast: False
n_classes: 21
#device
#eval_checkpoint: 
#eval_weights: 

training:

  find_best_lr: False
  batch_acc: 1
  batch_size: 64
  num_worker: 8
  pin_memory: True
  forward_hooks: False
  checkpoint: /projects/SemSeg/logs/RTFormer/20240411_112115_Shaper320Restart/checkpoints/last.pt
  caffe_pretrained: False
  max_iter: null #max total batch iteration
  aux_loss_weight: [1.0, 0.4]

  loss_function:
    ce: null
    params:
      reduction: "mean"
      ignore_index: 21

  optim:
    # SGD:
    #   momentum: 0.9
    #   weight_decay: 0.0005
    #   lr: 1.0e-3

    Adam:
      weight_decay: 0.0005
      lr: 1.0e-4

  lr_scheduler:
    PolynomialLR: 
      total_iters: 600
      power: 0.9

      


